apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerpytest-deployment
  labels:
    app: dockerpytest
spec:
  selector:
    matchLabels:
      app: dockerpytest
  template:
    metadata:
      labels:
        app: dockerpytest
    spec:
      containers:
      - name: dockerpytest
        image: ghcr.io/kjetpett/docker_pytest:latest
        imagePullPolicy: Always
      imagePullSecrets:
      - name: ghcr-login-secret