apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerpytest-deployment
  labels:
    app: dockerpytest
spec:
  selector:
    matchLabels:
      app: dockerpytest
  template:
    metadata:
      labels:
        app: dockerpytest
    spec:
      containers:
      - name: dockerpytest
        image: 3525trd:32000/dockerpytest:registry
        imagePullPolicy: Always
        ports:
        - containerPort: 80