apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: dockerpytest
  type: LoadBalancer
